### ISSUE TITLE
Search results problem

### ISSUE THREAD

**Issue by joviczarko** [SeanChDavis/_s-easy-digital-downloads#1]
Hey Sean, I have a problem with search
    This function is didn't defined I got errors when executing content-search.php:

<?php presentation_posted_on(); ?>

What this function was supposed to do?

**Comment by SeanChDavis** [comment]
That **certainly** wasn't supposed to be there. I'm managing quite a few repos with similar structures and I must have accidentally slipped that in there from a private repo I have called "Presentation." http://buildwpyourself.com/downloads/presentation/

Sorry about that! The file is now updated with the proper function prefix.
