### ISSUE TITLE
Customizer Warning: Creating default object from empty value

### ISSUE THREAD

**Issue by ghost** [SeanChDavis/_s-easy-digital-downloads#2]
Hi, Sean. When i'm trying to open theme customizer, it gives me Warning: Creating default object from empty value in C:\wamp\www\web\wp-content\themes_s-easy-digital-downloads\inc\customizer.php on line 84;
the same on line 140;
the same on line 175
the same on line 206.
Here is screenshot, call stack for all warnings is the same:
![warning](https://cloud.githubusercontent.com/assets/7829107/3684389/a5500a76-12fa-11e4-9e0c-1d47a6a7a6ef.jpg)
I run it on localhost website, Wamp Server Configuration is
Apache Version: 2.4.4 PHP Version: 5.4.16 MySQL Version: 5.6.12
Do you know how to fix it?

**Comment by SeanChDavis** [comment]
I'm sorry, bud. Just now seeing this. I check it out and push a fix.
